trigger:
  - main  # Runs on the main branch

pool:
  vmImage: 'windows-latest'  # ✅ Use Microsoft-hosted agent

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Install Java 17 properly with required architecture
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'  # ✅ Required input fixed
      jdkSource: 'PreInstalled'  # ✅ Uses Java from the hosted agent

  # ✅ Authenticate Maven (ensures dependencies resolve correctly)
  - task: MavenAuthenticate@0
    displayName: 'Authenticate Maven'

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: 'mubeenakausar267'
      scannerMode: 'CLI'
      configMode: 'manual'
      projectKey: 'mubeenakausar267_WebGoat'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=mubeenakausar267_WebGoat
        sonar.organization=mubeenakausar267
        sonar.host.url=https://sonarcloud.io
        sonar.login=$(SONAR_TOKEN)
        sonar.verbose=true
        sonar.scanner.force-deprecated-pipeline=true

  # ✅ Run Maven Build with Proper Test Skipping
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'Path'  # ✅ Ensures correct Java usage
      jdkUserInputPath: $(JAVA_HOME)  # ✅ Uses Java installed by JavaToolInstaller
      mavenVersionOption: 'Default'  # ✅ Uses Microsoft-hosted Maven
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=17 -DskipTests -Dmaven.test.skip=true -DskipITs -X -e'
      sonarQubeRunAnalysis: true

  # ✅ Run SonarCloud Analysis with Debug Logging
  - task: SonarCloudAnalyze@1
    displayName: "Run SonarCloud Analysis"
    inputs:
      extraProperties: |
        sonar.verbose=true

  # ✅ Publish SonarCloud Results
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
