trigger:
  - main  # Runs on the main branch

pool:
  name: Default

variables:
  SONAR_TOKEN: $(SonarCloudToken)  # Secret variable for SonarCloud
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Manually set JAVA_HOME
  - script: |
      echo "Setting JAVA_HOME manually"
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "##vso[task.prependpath]C:\Program Files\Java\jdk-17\bin"
    displayName: 'Set JAVA_HOME'

  # ✅ Manually set Maven Path
  - script: |
      echo "Setting Maven Path"
      echo "##vso[task.setvariable variable=MAVEN_HOME]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9"
      echo "##vso[task.prependpath]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin"
    displayName: 'Set Maven Path'


  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  # ✅ Run Maven with Correct Java Settings
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install -U'
      publishJUnitResults: false
      codeCoverageToolOption: 'JaCoCo'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx1024m'
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
