trigger:
  - main  # Runs on the main branch

pool:
  name: Default

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Ensure JAVA_HOME is Correctly Set
  - script: |
      echo Setting JAVA_HOME manually...
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "##vso[task.prependpath]C:\Program Files\Java\jdk-17\bin"
    displayName: 'Set JAVA_HOME'

  # ✅ Ensure MAVEN_HOME is Correctly Set
  - script: |
      echo Setting Maven Path...
      echo "##vso[task.setvariable variable=MAVEN_HOME]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9"
      echo "##vso[task.prependpath]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin"
    displayName: 'Set Maven Path'

  # ✅ **Fix Maven Command Syntax (No More Syntax Error)**
  - script: |
      echo Forcing Maven Compiler Plugin to use Java 17...
      call "D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn.cmd" -f pom.xml clean install -U -Dmaven.compiler.release=17
    displayName: 'Force Java 17 for Maven'
    workingDirectory: D:\agent\_work\1\s
    failOnStderr: false

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  # ✅ Run Maven Build with Java 17 Fix
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'Path'  # Ensures JAVA_HOME is respected
      mavenVersionOption: 'Path'  # Ensures MAVEN_HOME is used
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=17'
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
