trigger:
  - main  # Runs on the main branch

pool:
  name: Default

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Install Java 17 Correctly
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'  # ✅ Fixed the missing required input
      jdkSourceOption: 'PreInstalled'  # Use PreInstalled to avoid downloading

  # ✅ Ensure MAVEN_HOME is Set (Use Installed Maven)
  - task: UseDotNet@2
    inputs:
      packageType: 'maven'
      version: '3.9.9'
  
  # ✅ Verify Java and Maven Versions Before Build
  - script: |
      echo "Verifying Java and Maven Versions..."
      java -version
      mvn -version
    displayName: 'Verify Java and Maven'

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  # ✅ Run Maven Build
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=17'
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
