trigger:
  - main  # Runs on the main branch

pool:
   name: Default  # Using Local Agent

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Ensure Java 17 is Installed
  - script: |
      echo "Setting JAVA_HOME..."
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "##vso[task.prependpath]C:\Program Files\Java\jdk-17\bin"
    displayName: 'Set JAVA_HOME'

  # ✅ Ensure Maven is Installed
  - script: |
      echo "Setting Maven Path..."
      echo "##vso[task.setvariable variable=MAVEN_HOME]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9"
      echo "##vso[task.prependpath]D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin"
    displayName: 'Set Maven Path'

  # ✅ Clean up old test reports (Prevents Failsafe Plugin Errors)
  - script: |
      echo "Cleaning up old test reports..."
      if exist D:\agent\_work\1\s\target\failsafe-reports rmdir /s /q D:\agent\_work\1\s\target\failsafe-reports
    displayName: 'Clean Old Test Reports'

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: 'mubeenakausar267'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: 'mubeenakausar267_WebGoat'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=mubeenakausar267_WebGoat
        sonar.organization=mubeenakausar267
        sonar.token=$(SONAR_TOKEN)
        sonar.host.url=https://sonarcloud.io
        sonar.login=$(SONAR_TOKEN)


  # ✅ Run Maven Build with Java 17 and Proper Test Skipping
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'Path'
      jdkUserInputPath: 'C:\Program Files\Java\jdk-17'  # Explicit Java path
      mavenVersionOption: 'Path'  
      mavenPath: 'D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9'  # ✅ Correct Maven path
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=17 -DskipTests -Dmaven.test.skip=true -DskipITs -X -e'  # ✅ Full test skipping
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
