trigger:
  - main  # Runs on the main branch

pool:
  name: Default

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Set JAVA_HOME Environment Variable
  - powershell: |
      Write-Host "Setting JAVA_HOME..."
      [System.Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Program Files\Java\jdk-17", "Process")
      $env:Path += ";C:\Program Files\Java\jdk-17\bin"
      Write-Host "JAVA_HOME is set to: $env:JAVA_HOME"
    displayName: 'Set JAVA_HOME'

  # ✅ Set MAVEN_HOME Environment Variable
  - powershell: |
      Write-Host "Setting MAVEN_HOME..."
      [System.Environment]::SetEnvironmentVariable("MAVEN_HOME", "D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9", "Process")
      $env:Path += ";D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin"
      Write-Host "MAVEN_HOME is set to: $env:MAVEN_HOME"
    displayName: 'Set Maven Path'

  # ✅ Run Maven Command Using PowerShell
  - powershell: |
      Write-Host "Forcing Maven Compiler Plugin to use Java 17..."
      & "D:\WebGoat\apache-maven-3.9.9-bin\apache-maven-3.9.9\bin\mvn.cmd" -f "pom.xml" clean install -U "-Dmaven.compiler.release=17"
    displayName: 'Force Java 17 for Maven'
    workingDirectory: D:\agent\_work\1\s
    failOnStderr: false

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  # ✅ Run Maven Build with Java 17 Fix
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'Path'  # Ensures JAVA_HOME is respected
      mavenVersionOption: 'Path'  # Ensures MAVEN_HOME is used
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=17'
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
