trigger:
  - main  # Runs on the main branch

pool:
  #vmImage: 'Default'  # Runs on free Microsoft-hosted agent= ubuntu-latest
  name: Default

variables:
  SONAR_TOKEN: $(SonarCloudToken)  # Secret variable for SonarCloud
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Install Java 17 Using JavaToolInstaller (Replaces UseJavaVersion)
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
      jdkSource: 'PreInstalled'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  - task: Maven@3  # Change to Gradle if needed
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install -U'  # Added `-U` to force update dependencies
      publishJUnitResults: false
      codeCoverageToolOption: 'JaCoCo'
      javaHomeOption: 'Path'  # Explicitly set Java Home option
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx1024m'
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
