trigger:
  - main  # Runs on the main branch

pool:
  vmImage: 'windows-latest'  # ✅ Use Microsoft-hosted agent with Java preinstalled

variables:
  SONAR_TOKEN: $(SonarCloudToken)
  SONAR_PROJECT_KEY: 'mubeenakausar267_WebGoat'
  SONAR_ORG: 'mubeenakausar267'

steps:
  - checkout: self

  # ✅ Set Java Version (Prefer Java 23, Fallback to 17 if Not Available)
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '23'  # ✅ Use Java 23
      jdkArchitecture: 'x64'
      jdkSource: 'PreInstalled'

  # ✅ Verify Java & Maven Versions Before Build
  - script: |
      echo "Verifying Java and Maven Versions..."
      java -version
      mvn -version
    displayName: 'Verify Java and Maven'

  # ✅ Prepare SonarCloud Analysis
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: '$(SONAR_ORG)'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliprojectKey: '$(SONAR_PROJECT_KEY)'
      projectName: 'WebGoat'
      extraProperties: |
        sonar.projectKey=$(SONAR_PROJECT_KEY)
        sonar.organization=$(SONAR_ORG)
        sonar.sources=.

  # ✅ Run Maven Build with Java 23
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: false
      javaHomeOption: 'Path'  # Ensures JAVA_HOME is respected
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx1024m -Dmaven.compiler.release=23'  # ✅ Use Java 23 for Maven
      sonarQubeRunAnalysis: true

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
